#cloud-config
locale: ja_JP.UTF-8
 
rh_subscription:
  username: ${rhn_username}
  password: '${rhn_password}'
  auto-attach: False
  add-pool: [ '${rh_subscription_pool_id}' ]
runcmd:
 - subscription-manager repos --disable="*"
 - subscription-manager repos --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms" --enable="rhel-7-fast-datapath-rpms" --enable="rhel-7-server-ansible-2.4-rpms"
 - subscription-manager repos --enable="rhel-7-server-ose-${openshift_major_version}-rpms"
 - yum -y install openshift-ansible atomic-openshift-clients
